---
title: "Projects"
subtitle: "Repo for all my Projects"
# use quarto markdown to 
---

# DS150 Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)

# DS250 Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)

# DS350 Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)

# DS460 Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)

# CSE110 Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)

# CSE111 Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)

# CSE450 Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)

# ITM111 Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)

# ITM220 Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)


# Data Science Society Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)

# Personal Projects
## Repo for all my Projects

- [Project 1](/Projects/project1.qmd)
- [Project 2](/Projects/project2.qmd)
- [Project 3](/Projects/project3.qmd)
- [Project 4](/Projects/project4.qmd)
- [Project 5](/Projects/project5.qmd)