---
layout: cv
title: Resume
---
# Jonathan Ascona
Physicist, Mathematician, Cambridge professor.

<div id="webaddress">
<a href="jonathanascona01@gmail.com">jonathanascona01@gmail.com</a>
| <a href="https://www.linkedin.com/in/jonathan-ascona/">My LinkedIn Profile</a>
    <a href="https://app.joinhandshake.com/profiles/uq5mvg">Handshake</a>
</div>


## Currently

Standing on the shoulders of giants

### Specialized in

Laws of motion, gravitation, minting coins, disliking [Robert Hooke](http://en.wikipedia.org/wiki/Robert_Hooke)


### Research interests

Cooling, power series, optics, alchemy, planetary motions, apples.


## Education

__Bachelor's Degree - Data Science (Anticipated)__

*Brigham Young University - Idaho, Rexburg,ID*
`January 2022 - Present`




__Associate's Degree - Associate of Applied Science__

*Brigham Young University - Idaho, Rexburg,ID*
`January 2022 - July 2024`


## Awards

`October 2024`
i-Hack Hackathon 2024, *1st Place in Streamlit UI Category*, BYU-Idaho
'https://github.com/jonathanascona/iHack-Hackathon-2024-Project'



## Courses


### DS150 - Data Intuition & Insight

`1669`
Newton Sir I, De analysi per æquationes numero terminorum infinitas. 

`1669`
Lectiones opticæ.

etc. etc. etc.

### DS250 - Data Science Programming

### DS350 - Data Wrangling/Visualization

### DS460 - Big Data Programming

`2012`
Infinitesimal calculus for solutions to physics problems, [SMBC](http://www.techdirt.com/articles/20121011/09312820678/if-patents-had-been-around-time-newton.shtml) patent 001

### CSE110 - Intro to Programming

### CSE111 - Programming with Functions

### CSE450 - Machine Learning

### ITM111 - Introduction to Databases

### ITM220 - SQL


<!-- ### Footer

Last updated: May 2013 -->